src/components/ui/DropDownWithIcon.tsx, src/utils/type.d.ts
<br/>
DropDown 관련 타입 에러 수정 
<br/>
- utils > type.d.ts 파일 생성 & DropDown 관련 타입 추가 
- DropDownWithIcons 컴포넌트 에러 수정 
<br/>
<br/>
=> fix: DropDown관련 타입 공통으로 분리

src/app/layout.tsx, src/components/Header.tsx, tailwind.config.ts
feature-common
<br/>
- 공통 반응형 container 추가 
<br/>
- tailwind.config.ts 에 커스텀 container 클래스 추가 
- app > layout.tsx에 container 추가 
<br/>
<br/>
=> Design: 공통 반응형 container 추가

src/app/project/crews/page.tsx, src/app/project/layout.tsx, src/app/project/notice/page.tsx, src/app/project/page.tsx, src/app/project/setting/page.tsx, src/app/project/task/page.tsx, src/components/project/layout/ProjectInfo.tsx, src/components/project/layout/ProjectNavTab.tsx, src/components/ui/BackNav.tsx, src/store/ProjectNavTabStateStore.tsx, src/utils/common.ts, src/utils/type.d.ts
- feature-project
<br/>
1. 프로젝트 상세 페이지 레이아웃 추가
2. 등급배지 반응형으로 수정 
3. 페이지 공통 '뒤로 가기' 버튼 추가 
4. 프로젝트 상세페이지 내 업무/크루/알림/프로젝트 설정 라우트 추가 
<br/>
- ### src/app/project/layout.tsx
-  프로젝트 상세페이지 내 레이아웃 추가
- ### src/components/project/layout/ProjectInfo.tsx
- 프로젝트 상세페이지 상단 프로젝트 정보 요약 컴포넌트 
- ### src/components/project/layout/ProjectNavTab.tsx
- 프로젝트 상세페이지 내  업무/크루/알림/프로젝트 설정 nav탭 컴포넌트
- ### src/store/ProjectNavTabStateStore.tsx
- 프로젝트 nav탭 라우트 정보 및 활성화된 라우트 상태관리 store 
- ### src/utils/type.d.ts
<br/>
- ### src/utils/common.ts : makeBadgeSize 수정 
-  스크린사이즈 달라질때마다 다른 버튼을 렌더링하도록 작업하는것이 번거로워서 버튼 사이즈별 반응형 사이즈를 추가했습니다. 
<br/>
-  ### src/components/ui/BackNav.tsx
- 라우트를 props로 받을 수 있는 페이지 공통 뒤로가기 버튼입니다. (게시글 상세 페이지 등에 사용 가능)
<br/>
- ### …
=> Feature project

src/app/register/page.tsx, src/components/user/form/FormButton.tsx, src/components/user/form/Input.tsx, src/components/user/form/MultiSelect.tsx, src/components/user/form/PasswordInput.tsx, src/components/user/form/Select.tsx, src/components/user/form/TextArea.tsx, src/components/user/register/RegisterForm.tsx
feature-user
<br/>
기존에 만들었던 회원가입 페이지 반응형 고려하여 변경
<br/>
- src/components/user/form 항목들
- src/components/user/register/RegisterForm.tsx
- src/app/register/page.tsx
<br/>
close oneMonthProject/Front#6
<br/>
=> fix: 회원가입 반응형으로 변경

src/app/login/page.tsx, src/app/register/page.tsx, src/components/user/form/MultiSelect.tsx, src/components/user/form/Select.tsx, src/components/user/login/LoginForm.tsx, src/components/user/register/RegisterForm.tsx, src/store/UserStateStore.tsx, src/utils/type.d.ts
feature-user
<br/>
- 기존 MultiSelect, Select Component 에서 useReoilState 를 사용하던 부분을 굳이 전역에서 저장할 필요가 없으므로 useState 로 변경
- 로그인 페이지 구현
- 모바일일 경우 회원가입 밑에 링크 hidden 처리
<br/>
- ### src/component/user/form/Select.tsx
- ### src/component/user/form/MultiSelect.tsx
- ### src/component/user/register/RegisterForm.tsx
- ### src/store/UserStateStore.tsx
-  MultiSelect, Select props 수정으로 변경
- ### src/component/user/login/LoginForm.tsx
- ### src/app/register/page.tsx
-  모바일일경우 링크 hidden 처리
- ### src/app/login/page.tsx
-  로그인 페이지 구현
- ### src/util/type.d.ts
-  간격 변경
<br/>
<br/>
=> feat: 로그인 페이지 추가 및 Select props 변경

src/components/ui/Avatar.tsx
feature-common
<br/>
사용자의 프로필 사진 등 보여주는 부분을 공통 component 로 만들면 좋겠다는 의견을 받아 구현하였습니다.
Avatar component 에 src 를 넣으면 해당 이미지가 보여주고 null 로 넣으면 기존 빈 프로필을 보이게 반응형으로 구현하였습니다.  
<br/>
- ### src/component/ui/Avatar.tsx
<br/>
<br/>
=> feat: add Avatar component

src/app/login/page.tsx, src/app/register/page.tsx, src/app/user/layout.tsx, src/app/user/setting/page.tsx, src/components/user/login/LoginForm.tsx, src/components/user/profile/ProfileForm.tsx, src/components/user/register/RegisterForm.tsx
feature-user
<br/>
- 기존 로그인, 회원가입 페이지가 tablet 일 때 중앙이 맞지 않아 스타일 변경
- 프로필 수정 페이지 구현
<br/>
- ### src/app/login/page.tsx
- ### src/app/register/page.tsx
- ### src/components/user/login/LoginForm.tsx
- ### src/components/user/register/RegisterForm.tsx
-  중앙에 위치하도록 스타일 변경
- ### src/app/user/layout.tsx
-  기존 project layout 과 동일하나 우선은 이전페이지로 돌아가도록 구현
- ### src/app/user/setting/page.tsx
- ### src/components/user/profile/ProfileForm.tsx
-  프로필 수정 페이지 구현
<br/>
<br/>
=> feat: 프로필 수정 페이지 구현

.env.development, .env.production
<br/>
<br/>
- 개발용 환경변수 (npm run dev시 적용)
- 배포용 환경변수 (npm run build시 적용) 
<br/>
<br/>
=> chore: .env 파일 추가

.github/workflows/node.js.yml, .idea/.gitignore, .idea/Front.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
=> test commit

.github/workflows/node.js.yml, package-lock.json
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
=> package-lock.json 파일 추가

src/components/ui/Modal.tsx
- feature-project-2 
<br/>
<br/>
- 모달 열리는 위치를 top:0px 으로 고정 
<br/>
<br/>
=> fix: 프로젝트 상세 > 알림 모달 버그 수정

src/app/signup/page.tsx, src/app/user/profile/page.tsx, src/components/header/UserMenu.tsx, src/components/ui/Avatar.tsx, src/components/ui/MultiSelect.tsx, src/components/ui/Select.tsx, src/components/user/TechStackBadge.tsx, src/components/user/profile/ProfileCard.tsx, src/components/user/profile/UserHistory.tsx, src/components/user/profile/UserProjectInfo.tsx, src/components/user/signup/SignInForm.tsx, src/utils/common.ts
feature-user
<br/>
<br/>
useState 제거
<br/>
스타일 변경
<br/>
register -> signup
<br/>
기존 pr 에서 피드백 받은 사항 수정하고 회원가입 path 가 잘못되어 수정해서 올립니다.
진행중 oneMonthProject/Front#19
<br/>
=> 프로필 페이지 퍼블리싱 및 회원가입 path 변경

.gitignore, package-lock.json
feature-user
<br/>
<br/>
기존 pr 에서 package-lock.json 누락으로 git action 에서 오류가 나 추가해서 올립니다.
merge 는 할게요..
<br/>
=> fix: add package-lock.json

src/components/user/register/RegisterForm.tsx
feature-user
<br/>
<br/>
<br/>
죄송해요.. 제가 빠트려서 이 부분도 강제 merge 하겠습니다..
<br/>
=> fix: remove unused code

src/app/register/page.tsx, src/components/user/register/RegisterForm.tsx
feature-post
<br/>
<br/>
<br/>
<br/>
완료 oneMonthProject/Front#19
<br/>
=> feat: add register page

src/app/project/crews/[userId]/layout.tsx, src/app/project/crews/[userId]/page.tsx, src/components/project/crews/CrewList.tsx, src/components/project/crews/detail/CrewTaskHistory.tsx, src/components/project/crews/detail/CrewTaskHistoryPagination.tsx, src/components/project/crews/detail/LeaveProjectButton.tsx, src/components/project/crews/detail/ProfileSection.tsx, src/components/ui/Button.tsx, src/components/ui/badge/ProjectRoleBadge.tsx, src/components/ui/badge/TaskStatusBadge.tsx, tailwind.config.ts
feature-project-crews
<br/>
<br/>
<br/>
<br/>
실수로 이전에 merge한 내용까지 같이 들어갔네요.. 변경된 내용은 위에 쓴게 전부입니다. 
<br/>
=> Feature project crews

src/app/login/page.tsx, src/components/user/profile/ProfileCard.tsx, src/components/user/profile/UserProjectInfo.tsx
feature-user
<br/>
<br/>
href 변경
<br/>
badge 로 표현
<br/>
<br/>
=> 로그인 하단 링크 변경 및 프로필 신뢰등급 badge 로 표현 

src/app/login/page.tsx, src/app/signup/page.tsx, src/app/user/layout.tsx, src/app/user/setting/page.tsx, src/components/main/postCard/PostCard.tsx, src/components/main/posts/TechStackSelect.tsx, src/components/ui/MultiSelect.tsx, src/components/ui/Select.tsx, src/utils/common.ts
feature-common
<br/>
<br/>
로그인/회원가입/프로필 수정 화면에서 기존 가운데 정렬하는 방법이 tablet 을 가로모드 했을 경우 등 잘려서 수정
<br/>
main 의 게시글 부분이 Link 삽입 이후 mobile 일 때 이상하게 변형되어 수정
main 의 기술스택 컴포넌트가 일부 mobile 에서 모든 항목이 나오지 않아 media query 조건 수정
Image "lg" 일 때 mobile 크기 수정
<br/>
특정 필드로 객체를 비교하게 설정하는 by 프로퍼티 추가
<br/>
진행중 oneMonthProject/Front#57
<br/>
=> 스타일 조정 및 Select 컴포넌트 특정 필드로 객체를 비교하게 설정

src/components/project/task/TaskSectionHeader.tsx, src/components/project/task/milestone/MilestoneModalContent.tsx, src/components/project/task/task/TaskCardMenu.tsx, src/components/project/task/task/TaskModal.tsx, src/components/project/task/task/TaskModalContent.tsx, src/store/project/task/TaskStateStore.tsx
feature-project-task-2
<br/>
<br/>
담당자 Select 로 변경 및 MilestoneStateStore 와 이름 맞추기 위해 TaskStateStore 로 변경
<br/>
업데이트 부분 피드백 받아 스타일 수정
<br/>
<br/>
이미 MilestoneCard 에서 build 오류가 나서 배포된 환경에서 화면이 보이지 않고 있습니다.. 
<br/>
=> 업무의 담당 Select 로 변경 및 업데이트 부분 스타일 수정

src/components/project/task/milestone/MilestoneCard.tsx
feature-bugfix
<br/>
<br/>
- 마일스톤 카드 클릭 이벤트 타겟 타입 수정했습니다 
<br/>
- 어제 올리신 pr(#59) 빌드가 실패해서 에러 수정했습니다. 
<br/>
=> fix: MilestoneCard 빌드 에러 수정

src/app/project/setting/page.tsx, src/components/project/setting/ProjectSettingForm.tsx, src/components/ui/Select.tsx
feature-project-setting
<br/>
<br/>
min-h 있던 것 제거했습니다.
<br/>
프로젝트 정보 설정 부분과 종료 버튼을 추가했습니다.
<br/>
진행중 oneMonthProject/Front#57
<br/>
=> 프로젝트 설정 탭 content 추가

src/components/ui/form/NickNameField.tsx, src/components/user/profile/ProfileCard.tsx, src/components/user/profile/ProfileForm.tsx, src/components/user/signup/SignUpForm.tsx, src/hooks/useProfileInfo.tsx, src/mocks/handlers.ts, src/service/user.ts, src/utils/authApi.ts, src/utils/common.ts, src/utils/type.d.ts, tsconfig.json
feature-service-user
<br/>
<br/>
내 프로필, 토큰 재발급, 닉네임 중복체크 테스트 추가 및 useProfileInfo 추가
<br/>
회원가입 페이지 내의 유효성 체크 로직 구현 및 닉네임 중복체크 서비스 연결
common.ts 에 getSelectItemValue 추가
<br/>
TrustGradeItem, PositionItem, TechStackItem, ProfileInfo interface 추가 및 내 프로필 서비스 연결
bigInt 값을 직접적으로 사용하려면 최소 es2020 이어야 한다고 해서 테스트 하느라 버전 올렸는데 테스트 끝나고 문제가 된다면 다시 es6 으로 변경하겠습니다.
<br/>
authApi 의 response 를 가로채서 인증 체크 후 재발급하는 부분은 msw 로 테스트 해보려고 했는데 msw 가 뒤늦게 연결 되는건지  처음에는 404 뜨고.. 그 이후에나 handler  로 설정한 값이 오는 것 같습니다..ㅠㅠ 이 부분은 서버 연결 후에 다시 테스트 해보도록 하겠습니다.
<br/>
> 필요한 경우 추가 작업이나 변경 사항을 추적하기 위해 Todo 목록을 여기에 추가할 수 있습니다. 
user 부분 서비스 연결하면서 추가적으로 필요한 부분 구현한 뒤 게시글 쪽 작업하겠습니다.
=> 테스트 handler 추가 및 회원가입 내 프로필 서비스 연결

src/app/layout.tsx, src/components/ui/Snackbar.tsx, src/components/ui/form/NickNameField.tsx, src/components/user/profile/ProfileForm.tsx, src/components/user/profile/UserHistory.tsx, src/components/user/signup/SignUpForm.tsx, src/mocks/handlers.ts, src/store/MainStateStore.tsx, src/utils/common.ts, src/utils/type.d.ts
feature-service-user
<br/>
<br/>
```
const setSnackbar = useSetRecoilState(snackbarState);
setSnackbar({ show: true, type: "ERROR", content: "닉네임을 입력해주세요." });
```
이런식으로 설정하면 Snackbar 나오게 설정했습니다. duration  도 주는 것이 가능합니다.
<br/>
프로필 수정 및 회원 가입 시 validation 체크 하는 부분에 Snackbar 적용
<br/>
프로젝트 이력 상태 그냥 영어 코드를 받고 프론트에서 처리하기로 하여 수정
<br/>
진행중 #75 
<br/>
=> Snackbar 추가 및 적용 & 사용자 프로젝트 이력 상태 타입 변경

jest.config.ts, src/mocks/handlers/index.ts, src/mocks/handlers/projectHandlers.ts, src/mocks/handlers/userHandler.ts, src/mocks/index.ts, src/mocks/server.ts, src/mocks/worker.ts, src/utils/common.ts
<br/>
<br/>
- 기존에 한 handler로 합쳐져 있던 사용자, 프로젝트 api 테스트 핸들러를 projectHandler, userHandler로 분리했습니다 
<br/>
- 기존 msw에서 제공하는 json메서드로는 bigint데이터 다룰 수 없어서, bigint number로 전환하는 메서드로 직접 json 변환해서 body에 넣어줄수 있게 수정했습니다 
<br/>
- swiper가 테스트시 모킹이 따로 필요해서 jest.config.ts 파일 수정했는데, 아직 안됩니다.. 일단 swiper 포함된 컴포넌트는 테스트 안하고 있습니다
<br/>
<br/>
=> api 테스트 핸들러 분리 & swiper 모킹 관련 설정 수정

__tests__/project/ProjectList.test.tsx, __tests__/project/task/ProjectTask.test.tsx, src/components/project/layout/ProjectInfo.tsx, src/components/project/task/milestone/MilestoneCard.tsx, src/components/project/task/milestone/MilestoneCardMenu.tsx, src/components/project/task/milestone/MilestoneModal.tsx, src/components/project/task/milestone/MilestoneModalContent.tsx, src/components/project/task/milestone/MilestoneSection.tsx, src/components/project/task/milestone/Milestones.tsx, src/mocks/handlers/projectHandlers.ts, src/service/project.ts, src/store/project/task/MilestoneStateStore.tsx, src/utils/common.ts, src/utils/type.d.ts
<br/>
<br/>
- 테스트용 랜덤 bigint id generator 추가 & id 100개 생성하는 코드 테스트 파일에 추가 (배포시 삭제 필요) 
<br/>
- 마일스톤 목록 조회 테스트 api 연결 
- 마일스톤 데이터 객체 실제 응답값에 맞게 수정 
<br/>
<br/>
<br/>
<br/>
=> 프로젝트 상세 > 마일스톤 목록 조회 api 연결 

src/app/signup/page.tsx, src/app/user/profile/page.tsx, src/app/user/setting/page.tsx, src/components/header/Header.tsx, src/components/header/RegisterNav.tsx, src/components/header/UserMenu.tsx, src/components/main/myProjectPost/MyProjectPosts.tsx, src/components/post/register/RegisterForm.tsx, src/components/project/setting/ProjectSettingForm.tsx, src/components/project/task/milestone/MilestoneModalContent.tsx, src/components/project/task/task/TaskModalContent.tsx, src/components/ui/Snackbar.tsx, src/components/ui/form/CalendarInput.tsx, src/components/user/profile/ProfileCard.tsx, src/components/user/profile/ProfileForm.tsx, src/components/user/profile/UserHistory.tsx, src/components/user/signup/SignUpForm.tsx, src/hooks/useProfileInfo.tsx, src/mocks/handlers/userHandler.ts, src/service/logout.ts, src/service/user.ts, src/store/project/task/TaskStateStore.tsx, src/utils/authApi.ts
feature-service-user
<br/>
<br/>
빌드 오류 수정 및 authApi, RegisterNav, Snackbar 변경
<br/>
날짜 타입 Date -> string 으로 변경
<br/>
user 부분 get 을 데이터 가져오는 부분 SSR 로 변경
<br/>
화면공유로 자세히 설명해주셔서 감사합니다. Next.JS 는 뭔가 할 때 마다 찾아보며 하고 있기는 한데 아직도 개념이 많이 부족한 것 같습니다.
데이터를 불러오는 부분은 변경 완료했지만 로그아웃 및 저장하는 부분은 조금 더 찾아보고 수정하도록 하겠습니다.
진행중 #75
<br/>
=> SSR 로 변경 및 날짜 타입 Date -> string 으로 변경

src/components/project/task/milestone/MilestoneCard.tsx, src/components/project/task/milestone/MilestoneCardMenu.tsx, src/components/project/task/milestone/MilestoneSection.tsx, src/components/project/task/milestone/Milestones.tsx, src/mocks/handlers/projectHandlers.ts, src/store/project/task/MilestoneStateStore.tsx, src/utils/common.ts, src/utils/type.d.ts
<br/>
<br/>
<br/>
- 데이터 수정 
- 수정한 데이터 전역 상태값 및 ui 컴포넌트에 반영 
- 마일스톤 상태값 뱃지 추가 
- 진행중인 마일스톤 중 가장 빠른날짜로 active 상태 초기화 기능 추가 
<br/>
<br/>
=> 프로젝트 상세 > 마일스톤 progressStatus 반영

src/components/header/RegisterNav.tsx, src/components/main/postCard/PostCard.tsx, src/components/main/posts/PositionDropdown.tsx, src/components/main/posts/PostList.tsx, src/components/main/posts/Posts.tsx, src/components/main/posts/Search.tsx, src/components/main/posts/TechStackSelect.tsx, src/components/post/buttonSection/ButtonSection.tsx, src/components/ui/Snackbar.tsx, src/components/user/profile/ProfileCard.tsx, src/components/user/profile/UserHistory.tsx, src/hooks/usePositionList.tsx, src/mocks/handlers/commonHandlers.ts, src/mocks/handlers/index.ts, src/mocks/handlers/postHandlers.ts, src/mocks/handlers/userHandler.ts, src/service/logout.ts, src/service/post.ts, src/service/setting.ts, src/service/user.ts, src/store/MainStateStore.tsx, src/utils/common.ts, src/utils/type.d.ts
<br/>
<br/>
필요없는 코드 제거 및 코드 리팩토링
<br/>
TechStackItem 수정
<br/>
메인 화면의 게시글 검색 조회 서비스 연결
기술스택 연결은 백엔드분들과 협의 후에 결과값으로 연결 예정(참고 이슈: oneMonthProject/Backend#268)
<br/>
기존 commit 들과 합치는 과정에서 생긴 오류로 기존 ProjectInfo 안의 값 되돌리고 PostProjectInfo 생성
<br/>
진행중 #75
<br/>
=> 메인 게시물 검색 조회 서비스 연결

src/app/globals.css, src/components/project/task/milestone/MilestoneAddButton.tsx, src/components/project/task/milestone/MilestoneCard.tsx, src/components/project/task/milestone/MilestoneCardMenu.tsx, src/components/project/task/milestone/MilestoneSection.tsx, src/components/project/task/milestone/Milestones.tsx, src/components/ui/CustomSwiper.tsx, src/hooks/useProjectInfo.tsx, src/mocks/handlers/projectHandlers.ts, src/store/project/crews/ProjectUserAuthStateStore.tsx, src/store/project/task/MilestoneStateStore.tsx, src/utils/type.d.ts
<br/>
<br/>
- 마일스톤 선택시 해당 마일스톤 카드가 슬라이드 가장 첫번째 오도록 수정
<br/>
- 사용자 프로젝트 권한 데이터 테스트 api 및 데이터 객체에 반영
- 사용자 프로젝트 권한 관리하는 ProjectUserAuthStateStore.tsx 추가 
- useProjectInfo 훅에서 사용자 프로젝트 권한 ProjectUserAuthStateStore에 저장하도록 수정 
- 사용자 프로젝트 권한에 따라 마일스톤 생성/수정/삭제 기능 활성화되도록 수정 
<br/>
<br/>
=> 프로젝트 상세 > 마일스톤 선택시 슬라이드 이동 기능 추가 & 마일스톤 생성/수정/삭제 권한 적용 

src/components/main/myProjectPost/MyProjectPosts.tsx, src/components/project/layout/ProjectInfo.tsx, src/components/project/task/milestone/MilestoneAddButton.tsx, src/components/project/task/milestone/MilestoneCardMenu.tsx, src/components/project/task/milestone/MilestoneModal.tsx, src/components/project/task/milestone/MilestoneModalContent.tsx, src/components/project/task/milestone/Milestones.tsx, src/hooks/useCreateMilestone.tsx, src/hooks/useProjectCrewList.tsx, src/hooks/useProjectInfo.tsx, src/hooks/useUpdateMilestone.tsx, src/mocks/handlers/index.ts, src/mocks/handlers/project/index.ts, src/mocks/handlers/project/projectHandlers.ts, src/mocks/handlers/project/projectMilestoneHandlers.ts, src/service/project/milestone.ts, src/service/project/project.ts, src/utils/common.ts
<br/>
<br/>
- 권한 필요한 컴포넌트별로 조회하도록 수정
<br/>
- projectHandler, projectMilestoneHandler 분리 
- 마일스톤 생성/수정 hook 추가
- 프로젝트/마일스톤 서비스 파일 분리 
- 오늘날짜 문자열반환하는 함수 버그 수정 
<br/>
<br/>
<br/>
=> 프로젝트 상세 > 프로젝트 내 권한 조회 로직 수정 & 마일스톤 생성/수정 코드 추가 

src/components/user/login/LoginForm.tsx, src/service/login.ts, src/service/signup.ts
<br/>
<br/>
URI 변경 및 login response 값 변경
<br/>
env 파일은 올려주신?다고 해서 일단 안올렸습니다.
<br/>
=> URI 변경 및 login response 값 변경

src/app/api/setting/nickname/route.ts, src/app/api/user/history/route.ts, src/app/api/user/logout/route.ts, src/app/api/user/route.ts, src/app/api/user/simple/route.ts, src/components/header/UserMenu.tsx, src/components/main/myProjectPost/MyProjectPosts.tsx, src/components/main/postTabMenu/PostTabMenu.tsx, src/components/main/posts/PositionDropdown.tsx, src/components/main/posts/Posts.tsx, src/components/ui/form/NickNameField.tsx, src/components/user/profile/ProfileForm.tsx, src/components/user/profile/UserHistory.tsx, src/service/logout.ts, src/service/user.ts, src/utils/authApi.ts
<br/>
<br/>
필요없는 코드 제거
<br/>
사용자 메뉴 부분 서비스 연결(간단한 내 정보 조회 & 로그아웃)
로그인한 사용자만 프로젝트 탭 보이게 설정
<br/>
사용자 부분 서비스 연결(사용자 조회 & 사용자 프로젝트 이력 조회 & 닉네임 중복체크 & 사용자 정보 업데이트)
<br/>
진행중 #89
<br/>
=> 사용자 메뉴 부분, 사용자 부분 서비스 연결

src/components/header/UserMenu.tsx, src/components/main/postTabMenu/PostTabMenu.tsx, src/service/login.ts
<br/>
<br/>
서버측과 프론트측의 주소가 다를 경우 처리해줘야 하는 부분이 있어 처리했습니다.
백엔드 부분도 수정했습니다.
<br/>
메인 탭 렌더링 오류 수정
<br/>
진행중 #89 
<br/>
=> 로그인 시 credentials 옵션 추가 및 렌더링 오류 수정

src/components/ui/CommonPagination.tsx, src/utils/type.d.ts
<br/>
<br/>
- CommonPagination 컴포넌트에 props 추가해서 Pagination 설정 동적으로 할 수 있게 수정했습니다. 
<br/>
진행중 - #104 
<br/>
=> fix(공통): CommonPagination props로 paging하도록 수정

src/app/api/user/simple/route.ts, src/components/main/posts/PostList.tsx, src/service/login.ts, src/service/post.ts, src/service/setting.ts, src/utils/authApi.ts
feature-common
<br/>
<br/>
keyWord -> keyword 로 변경하고 한글깨지는 문제를 해결
<br/>
원래는 서버에서 Set-Cookie 로 보내면 자동으로 브라우저가 저장해주는 게 맞는데.. SSR 이라 그런지 그게 되지 않아서 수동으로 쿠키를 설정했습니다.
테스트도 해봤는데 일단 재발급 잘 되는 것 같아요 근데 백엔드 코드도 수정되어서 백엔드 배포는 다시 되어야 할 것 같아요.
<br/>
진행중 #103
<br/>
=> Refresh Token 쿠키 설정 및 전체 게시글 조회 parameter 수정

src/app/api/project/[slug]/route.ts, src/app/api/project/task/route.ts, src/components/main/myProjectPost/MyProjectPosts.tsx, src/components/project/task/task/TaskCard.tsx, src/components/project/task/task/TaskModal.tsx, src/service/project/project.ts, src/service/project/task.ts
<br/>
<br/>
<br/>
<br/>
진행중 - #104 
<br/>
=> 내 프로젝트 조회 paging 추가 & 프로젝트 업무 생성/삭제 api 연결

src/app/api/project/crewTaskHistory/route.ts, src/components/project/crews/detail/CrewTaskHistory.tsx, src/components/project/crews/detail/ProfileSection.tsx, src/components/ui/badge/CrewStatusBadge.tsx, src/hooks/useProjectCrewList.tsx, src/service/project/crews.ts, src/service/project/project.ts, src/utils/common.ts, src/utils/constant.ts, src/utils/type.d.ts
<br/>
<br/>
<br/>
<br/>
크루 업무 이력용 라우트 핸들러 추가했습니다(api/project/crewTaskHistory). 크루 업무 이력 저장 api 연동시 이 경로에 api 생성 부탁드려요  .
진행중 #104 
<br/>
=> 프로젝트 크루 상세 api 연동 

src/app/api/setting/[slug]/route.ts, src/components/main/posts/PositionDropdown.tsx, src/components/main/posts/PostList.tsx, src/components/main/posts/Posts.tsx, src/components/main/posts/TechStackDropdown.tsx, src/components/main/posts/TechStackSelect.tsx, src/components/post/infoSection/InfoSection.tsx, src/components/post/register/RegisterForm.tsx, src/service/post.ts, src/service/setting.ts, src/store/MainStateStore.tsx, src/utils/publicApi.ts, src/utils/type.d.ts
<br/>
<br/>
5b41c124bfea0b298de97da06f00567124eafd72, 8aa86cc88867da04109ea7f000cc2283889bbfe5
<br/>
52e2eb60c3983fa9dae47b74c82284efd6ae82bc
<br/>
진행중 #103 
<br/>
=> 메인 기술스택 서비스 연결 및 조회 조건 변경 & 게시글 작성 시 신뢰등급 리스트 수정

src/app/api/project/[slug]/route.ts, src/app/user/profile/page.tsx, src/app/user/setting/page.tsx, src/components/header/Header.tsx, src/components/header/UserMenu.tsx, src/components/main/posts/PostList.tsx, src/components/post/buttonSection/ButtonSection.tsx, src/components/ui/skeleton/AvatarSkeleton.tsx, src/components/user/profile/ProfileCardSkeleton.tsx, src/components/user/profile/ProfileFormSkeleton.tsx, src/components/user/profile/UserHistory.tsx, src/components/user/profile/UserHistorySkeleton.tsx, src/service/project/project.ts
feature-skeleton-user
<br/>
<br/>
493898cd9e980d25ad81273bd50fdc5b3febbff8, f1f347e13065354105beb3c587a677d1e4fba0ce
<br/>
b2403d3eae480e4f21d64b8b8b4fcdc546539ce8
<br/>
a0eb9d86c8c26640f9155bcd77b637ec583362ff
<br/>
진행중 #117 
<br/>
=> 프로필, 프로필 수정, Header 에 사용자 정보 부분에 Skeleton 추가 및 데이터 없을 때 메세지 보여주는 컴포넌트 추가

src/app/api/post/[slug]/route.ts, src/app/post/page.tsx, src/app/register/page.tsx, src/components/main/PostListSkeleton.tsx, src/components/main/postCard/PostCard.tsx, src/components/main/posts/Posts.tsx, src/components/main/posts/TechStackDropdown.tsx, src/components/main/posts/TechStackDropdownList.tsx, src/components/post/PostSkeleton.tsx, src/components/post/buttonSection/ButtonSection.tsx, src/components/post/infoSection/InfoSection.tsx, src/components/post/register/MultiPositionSelect.tsx, src/components/post/register/RegisterForm.tsx, src/components/post/register/TechStackSelect.tsx, src/components/post/register/TrustGradeSelect.tsx, src/components/post/titleSection/TitleSection.tsx, src/service/post/post.ts
feature-skeleton-post
<br/>
<br/>
d0a2ec9a3f56f8460c2e99e474d85292bf549899, df6b3ef8cd0f67d53e1ccb69676b012d638996f6
<br/>
366707b0319bcf12b0f9141d39c56cb6bbd4ae1c
<br/>
진행중 #117 
<br/>
=> 게시글 부분 Skeleton 추가 및 게시글 모집 상태 변경 서비스 연결

src/app/api/post/[slug]/route.ts, src/components/post/PostDetail.tsx, src/components/post/buttonSection/ButtonSection.tsx, src/service/post/post.ts, src/utils/type.d.ts
<br/>
<br/>
- PostInfo 의 completeStatus -> recruitmentStatus 로 변경
- 게시글 모집 상태 변경 후 ui 가 변하지 않은 항목 수정(query key 타입 수정)
<br/>
진행중 #121 
<br/>
=> 게시글 모집 상태 버그 수정

next.config.js, src/app/api/user/route.ts, src/components/user/profile/ProfileForm.tsx, src/service/user/user.ts, src/utils/authApi.ts, src/utils/publicApi.ts
feature-service-user
<br/>
<br/>
f7680d8368c992cc7bcd59a19c53e4bb5ffe4709
<br/>
1317387606c12fe854de375fd2745e65df1800c7
<br/>
진행중 #121 
<br/>
> 필요한 경우 추가 작업이나 변경 사항을 추적하기 위해 Todo 목록을 여기에 추가할 수 있습니다. 
기존 이미지가 있는데 삭제할 경우 s3 에서 해당 이미지를 삭제하도록 api 연결
=> 사용자 정보 수정에서 이미지도 수정하도록 연결 및 authApi & publicApi 의 content-type 로직 수정

next.config.js, src/app/error.tsx
feature-common
<br/>
<br/>
9e40009e54dec4cf09e9b2980bcf5ee9712142cc
<br/>
31036eb8a35821c70637fb14c974b09bc82f2d29
<br/>
<br/>
=> error.tsx 생성 및 next.config.js 변경

next.config.js, package-lock.json, src/app/project/page.tsx, src/components/header/Header.tsx, src/components/main/PostTabContents.tsx, src/components/main/myProjectPost/MyProjectPosts.tsx, src/components/project/task/milestone/MilestoneCard.tsx, src/components/project/task/milestone/MilestoneSection.tsx, src/components/project/task/milestone/Milestones.tsx, src/components/project/task/task/TaskSection.tsx, src/components/ui/skeleton/project/MilestoneCardSkeleton.tsx, src/components/ui/skeleton/project/ProjectInfoSkeleton.tsx, src/components/ui/skeleton/project/ProjectMilestoneSkeleton.tsx, src/components/ui/skeleton/project/ProjectNavTabSkeleton.tsx, src/components/ui/skeleton/project/index.tsx, src/hooks/useUpdateMilestone.tsx, src/service/post/post.ts, src/service/project/milestone.ts, src/service/project/task.ts
<br/>
<br/>
- c3e5d5c9f8b27acc365aec52100110df2ebc100e
<br/>
- db20aeb35844b4e7549fa6fd94bdb39691dcd0e3
<br/>
- 702672df7694e8df43a8b9ff3510b70d2925afff, 8652b1adbf1fe771aa05b67dd3c46947798888ca
<br/>
작업 양이 많아서 미리 좀 나눠서 커밋합니다 
<br/>
=> feat#125 프로젝트 도메인 스켈레톤 작업 및 기타 버그 수정

src/app/api/project/milestone/route.ts, src/app/api/project/task/route.ts, src/app/project/@crews/page.tsx, src/app/project/@task/page.tsx, src/app/project/page.tsx, src/components/header/Header.tsx, src/components/project/task/task/Tasks.tsx, src/components/ui/CommonPagination.tsx, src/components/ui/CustomSwiper.tsx, src/hooks/useUpdateMilestone.tsx, src/service/project/milestone.ts, src/utils/type.d.ts
<br/>
<br/>
useSearchParams 사용하는 컴포넌트를 Suspense로 묶지 않아서 발생하는 에러였네요. 일단 빌드에러 안나게만 조치해놓고
fallback은 후에 더 추가할 예정입니다. 자꾸 빌드 테스트하고 올리는걸 까먹네요..
<br/>
프로젝트 도메인 관련 자잘한 에러 수정했습니다. 사실 빌드에러랑 분리해서 pr 생성하려했는데 안 올린 파일때문에 빌드 에러 날까봐 그냥 합쳐서 올립니다.. 
<br/>
<br/>
이 Pr 먼저 approve 해주시고, 제가 main에 머지하고나면 main으로 다시 rebase 하셔서 pr 머지하심 될 것 같아요. 
<br/>
=> 빌드 에러 수정 및 기타 에러 수정 

src/components/user/profile/UserHistory.tsx, src/utils/type.d.ts
feature-user-post
<br/>
<br/>
userProjectHistoryId 가 proejctId 인 줄 알았는데 아니어서 백엔드 코드 수정하고 프론트도 수정하였습니다.
c575415e799c437e9583607070c2dad6a7033524
<br/>
<br/>
=> 사용자 프로젝트 이력 타입에 projectId 추가

package-lock.json, package.json, src/app/api/project/milestone/route.ts, src/components/project/task/milestone/MilestoneCard.tsx, src/components/project/task/milestone/MilestoneStatusSelector.tsx, src/components/project/task/milestone/Milestones.tsx, src/components/ui/CustomSwiper.tsx, src/hooks/useMilestoneList.tsx, src/hooks/useUpdateMilestone.tsx, src/service/project/milestone.ts, src/store/project/task/MilestoneStateStore.tsx
<br/>
> 마일스톤 수정/삭제 버그 수정 및 swiper 수정 
<br/>
<br/>
<br/>
<br/>
<br/>
=> fix: 마일스톤 수정/삭제 버그 수정

src/app/projectCrewDetail/layout.tsx, src/app/projectCrewDetail/page.tsx, src/components/project/crews/CrewList.tsx, src/components/project/crews/detail/CrewTaskHistory.tsx, src/components/project/crews/detail/ProfileSection.tsx, src/components/project/task/task/TaskCard.tsx, src/components/project/task/task/Tasks.tsx
<br/>
<br/>
- d5ce6b96999c1f72a2d3d8216471b80258e05b10
<br/>
- a1447ae04db9f5ef47698add65544d9680ce0267
<br>
**프로젝트 상세 페이지 layout과 크루 상세페이지 layout은 겹치면 안되서, 크루 상세 라우트를 분리했습니다(/project/crewDetail -> /projectCrewDetail)**
<br/>
- 3d4f8009b927e78c73bb9afb35a8ff56c01c460d
<br/>
#134 진행중 
<br/>
=> 프로젝트 상세 - 업무 목록 조회 버그 수정 & 크루 상세 라우트 구조 수정

src/app/api/project/confirm/[slug]/route.ts, src/app/project/@setting/page.tsx, src/components/main/myProjectPost/ParticipateNotice/ParticipateNotice.tsx, src/components/post/register/TrustGradeSelect.tsx, src/components/project/crews/detail/CrewTaskHistory.tsx, src/components/project/notice/NoticeItem.tsx, src/components/project/notice/NoticeList.tsx, src/components/project/notice/NoticeModal.tsx, src/components/project/notice/noticeModalContents/TaskPointSelector.tsx, src/components/project/setting/ProjectSettingForm.tsx, src/components/ui/badge/NoticeBadge.tsx, src/service/project/confirm.ts, src/store/project/notice/ProjectNoticeStateStore.tsx, src/utils/common.ts, src/utils/constant.ts, src/utils/type.d.ts
<br/>
- 0d9f4bc0fe40be09e587fca73a934a3ced84655b, 60f42b1ac98e64ea0afc9b3583d507d27614a2fb
- 1166ea1e52850074ba95426040b18088d7dfe054, 92dd4c36c5763d414eed4e4942e65ebe42f3a2fb
- 75adfa2aa13aae9cc9fe66fbe4108d6d54980fbe
- 8bb92d00488fd456abb98a4aecfc302f6263e883
<br/>
진행중 - #140 
<br/>
=> 프로젝트 설정 페이지 & 알림 컨펌 & 크루상세 이력 수정작업

src/app/api/project/confirm/[slug]/route.ts, src/app/api/project/crews/[slug]/route.ts, src/app/api/project/notice/[slug]/route.ts, src/app/api/project/notice/route.ts, src/components/project/crews/detail/CrewOutButton.tsx, src/components/project/crews/detail/CrewTaskHistory.tsx, src/components/project/crews/detail/ProfileSection.tsx, src/components/project/layout/ProjectInfo.tsx, src/components/project/notice/ManagerCheckIcon.tsx, src/components/project/notice/NoticeItem.tsx, src/components/project/notice/NoticeModal.tsx, src/components/project/notice/noticeModalContents/NoticeModalContents.tsx, src/components/project/notice/noticeModalContents/WthdrawSelector.tsx, src/components/project/task/milestone/MilestoneAddButton.tsx, src/components/project/task/milestone/MilestoneCard.tsx, src/components/project/task/milestone/MilestoneSection.tsx, src/components/project/task/task/TaskAddButton.tsx, src/components/ui/Button.tsx, src/components/ui/badge/ProjectRoleBadge.tsx, src/components/ui/skeleton/BadgeStyleSkeleton.tsx, src/components/ui/skeleton/project/MilestoneCardSkeleton.tsx, src/components/ui/skeleton/project/ProjectInfoSkeleton.tsx, src/components/ui/skeleton/project/ProjectMilestoneSkeleton.tsx, src/hooks/useUpsertTask.tsx, src/service/project/confirm.ts, src/service/project/crews.ts, src/service/project/notice.ts, src/store/project/notice/ProjectNoticeStateStore.tsx
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
=> 프로젝트 상세 - 탈퇴/강제탈퇴 api 연동 & 일부 스켈레톤 수정 
